package sumis;

import java.sql.*;
import java.util.Scanner;

public class OfficerMenu {

    private final Scanner sc = new Scanner(System.in);

    public void show() {
        while (true) {
            System.out.println("\n======= OFFICER MENU =======");
            System.out.println("1. Insert New Violation");
            System.out.println("2. View Vehicle History");
            System.out.println("3. Check Blacklist");
            System.out.println("4. View All Active Violations");
            System.out.println("5. Run Custom SQL");
            System.out.println("0. Logout");
            System.out.print("Choice: ");

            int choice = Integer.parseInt(sc.nextLine().trim());
            switch (choice) {
                case 1 -> insertViolation();
                case 2 -> viewVehicleHistory();
                case 3 -> checkBlacklist();
                case 4 -> viewActiveViolations();
                case 5 -> runCustomSQL();
                case 0 -> { return; }
                default -> System.out.println("Invalid option.");
            }
        }
    }

    // -- Core Officer Functions ------------------------------------------------

    private void insertViolation() {
        try {
            System.out.print("Enter Vehicle ID: ");
            int vehicleId = Integer.parseInt(sc.nextLine().trim());
            System.out.print("Enter Camera ID: ");
            int cameraId = Integer.parseInt(sc.nextLine().trim());
            System.out.print("Enter Violation Type ID (1=Speeding,2=Red Light,3=Wrong Side,4=No Helmet,5=Phone): ");
            int typeId = Integer.parseInt(sc.nextLine().trim());

            try (Connection conn = DBConnection.getConnection();
                 PreparedStatement ps = conn.prepareStatement(
                     "INSERT INTO Violation (VehicleID, CameraID, ViolationTypeID) VALUES (?,?,?)")) {
                ps.setInt(1, vehicleId);
                ps.setInt(2, cameraId);
                ps.setInt(3, typeId);
                ps.executeUpdate();
                System.out.println("[OK] Violation recorded. Fine auto-generated by trigger.");
            }
        } catch (Exception e) { System.err.println("Error: " + e.getMessage()); }
    }

    private void viewVehicleHistory() {
        try {
            System.out.print("Enter Registration No: ");
            String regNo = sc.nextLine().trim();
            String sql = """
                SELECT v.ViolationID, v.DateTime, vt.Description, f.Amount, f.Status, f.DueDate
                FROM Violation v
                JOIN Vehicle veh      ON v.VehicleID = veh.VehicleID
                JOIN ViolationType vt ON v.ViolationTypeID = vt.ViolationTypeID
                JOIN Fine f           ON f.ViolationID = v.ViolationID
                WHERE veh.RegistrationNo = ?
                ORDER BY v.DateTime DESC
                """;
            try (Connection conn = DBConnection.getConnection();
                 PreparedStatement ps = conn.prepareStatement(sql)) {
                ps.setString(1, regNo);
                ResultSet rs = ps.executeQuery();
                System.out.printf("%n%-5s %-22s %-25s %-10s %-8s %-12s%n",
                    "ID","DateTime","ViolationType","Amount","Status","DueDate");
                System.out.println("-".repeat(85));
                boolean found = false;
                while (rs.next()) {
                    found = true;
                    System.out.printf("%-5d %-22s %-25s %-10.2f %-8s %-12s%n",
                        rs.getInt("ViolationID"),
                        rs.getTimestamp("DateTime"),
                        rs.getString("Description"),
                        rs.getDouble("Amount"),
                        rs.getString("Status"),
                        rs.getDate("DueDate"));
                }
                if (!found) System.out.println("No violations found.");
            }
        } catch (Exception e) { System.err.println("Error: " + e.getMessage()); }
    }

    private void checkBlacklist() {
        try (Connection conn = DBConnection.getConnection();
             Statement st = conn.createStatement();
             ResultSet rs = st.executeQuery("""
                 SELECT b.BlacklistID, veh.RegistrationNo, o.Name, b.StartDate, b.Reason
                 FROM Blacklist b
                 JOIN Vehicle veh ON b.VehicleID = veh.VehicleID
                 JOIN Owner o     ON veh.OwnerID = o.OwnerID
                 ORDER BY b.StartDate DESC
                 """)) {
            System.out.printf("%n%-5s %-15s %-20s %-12s %-40s%n",
                "ID","RegNo","OwnerName","StartDate","Reason");
            System.out.println("-".repeat(95));
            while (rs.next()) {
                System.out.printf("%-5d %-15s %-20s %-12s %-40s%n",
                    rs.getInt("BlacklistID"),
                    rs.getString("RegistrationNo"),
                    rs.getString("Name"),
                    rs.getDate("StartDate"),
                    rs.getString("Reason"));
            }
        } catch (Exception e) { System.err.println("Error: " + e.getMessage()); }
    }

    private void viewActiveViolations() {
        try (Connection conn = DBConnection.getConnection();
             Statement st = conn.createStatement();
             ResultSet rs = st.executeQuery(
                 "SELECT * FROM vw_active_violations ORDER BY DateTime DESC LIMIT 20")) {
            System.out.printf("%n%-5s %-22s %-15s %-20s %-25s %-10s %-8s%n",
                "ID","DateTime","RegNo","Owner","ViolationType","Fine","Status");
            System.out.println("-".repeat(110));
            while (rs.next()) {
                System.out.printf("%-5d %-22s %-15s %-20s %-25s %-10.2f %-8s%n",
                    rs.getInt("ViolationID"),
                    rs.getTimestamp("DateTime"),
                    rs.getString("RegistrationNo"),
                    rs.getString("OwnerName"),
                    rs.getString("ViolationType"),
                    rs.getDouble("BaseFineAmount"),
                    rs.getString("FineStatus"));
            }
        } catch (Exception e) { System.err.println("Error: " + e.getMessage()); }
    }

    // -- Custom SQL ------------------------------------------------------------

    private void runCustomSQL() {
        System.out.println("\nEnter your SELECT query:");
        System.out.print("SQL> ");
        String sql = sc.nextLine().trim();
        if (sql.isEmpty()) { System.out.println("No query entered."); return; }
        if (!sql.trim().toUpperCase().startsWith("SELECT")) {
            System.out.println("[DENIED] Officer role allows SELECT queries only.");
            return;
        }
        try (Connection conn = DBConnection.getConnection();
             Statement st = conn.createStatement();
             ResultSet rs = st.executeQuery(sql)) {
            ResultSetMetaData meta = rs.getMetaData();
            int cols = meta.getColumnCount();
            System.out.println();
            for (int i = 1; i <= cols; i++)
                System.out.printf("%-20s", meta.getColumnName(i));
            System.out.println("\n" + "-".repeat(20 * cols));
            int rowCount = 0;
            while (rs.next()) {
                for (int i = 1; i <= cols; i++)
                    System.out.printf("%-20s",
                        rs.getString(i) != null ? rs.getString(i) : "NULL");
                System.out.println();
                rowCount++;
            }
            System.out.println("\n[" + rowCount + " row(s) returned]");
        } catch (Exception e) { System.err.println("SQL Error: " + e.getMessage()); }
    }
}
